.PHONY: build

build:
	yarn build

.PHONY: up

up:
	docker-compose up -d

.PHONY: down

down:
	docker-compose down

.PHONY: logs

logs:
	docker-compose logs -f

.PHONY: dev

dev:
	yarn dev

.PHONY: install

install:
	yarn